### ISSUE TITLE
안녕하세요. 이전에 HUFSummer Hackathon 세션 발표 했던 이태현이라고 합니다.

### ISSUE THREAD

**Issue by 0417taehyun** [yanghyen/Ohmygodlife_Back#1]
안녕하세요. 이전에 HUFSummer Hackathon 세션 발표 했던 이태현이라고 합니다.
채점을 위해 소스 코드를 보다가 [OpenAPI 키를 그대로 노출](https://github.com/yanghyen/Ohmygodlife_Back/blob/9b32e7a664fb37ceb6e47cff92464f14cc499210/index.js#L1
)하고 계셔서 이렇게 이슈에 남겨드려요.

해당 내용은 채점과는 무관한 부분이고, 만약 키를 따로 없애지 않으셨다면 혹여 예상치 못한 과금을 하시게 될 것 같아 염려가 되어 글 작성합니다.

여담이지만, `node_modules` 또한 `.gitignore` 같은 파일을 통해 GitHub 레포지토리에 업로드되지 않게 관리하면서, API 키 또한 `.env` 파일 등으로 환경 변수로 관리하여 `.gitignore` 파일에 등록해 GitHub 레포지토리에 업로드해서 노출되지 않게 관리하는 부분을 한 번 찾아보시면 이후에도 개발하실 때 큰 도움 되실 것 같습니다.

**Comment by yanghyen** [comment]
안녕하세요. 
대회 당일에 급하게 업로드하느라 api 키를 그대로 노출했네요.. 확인해보니 다행히 키는 자동으로 삭제된 것 같아요. 여담으로 알려주신 부분도 앞으로 개발할 때 참고하겠습니다! 바쁘실텐데 이메일로 해당 내용들 알려주셔서 감사합니다!! 


네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: ***@***.***>
받는사람: ***@***.***>
참조: ***@***.***>
날짜: 2023. 6. 29 00:11:18
제목: [yanghyen/Ohmygodlife_Back] 안녕하세요. 이전에 HUFSummer Hackathon 세션 발표 했던 이태현이라고 합니다. (Issue #1)

안녕하세요. 이전에 HUFSummer Hackathon 세션 발표 했던 이태현이라고 합니다.
채점을 위해 소스 코드를 보다가 OpenAPI 키를 그대로 노출하고 계셔서 이렇게 이슈에 남겨드려요.
해당 내용은 채점과는 무관한 부분이고, 만약 키를 따로 없애지 않으셨다면 혹여 예상치 못한 과금을 하시게 될 것 같아 염려가 되어 글 작성합니다.
여담이지만, node_modules 또한 .gitignore 같은 파일을 통해 GitHub 레포지토리에 업로드되지 않게 관리하면서, API 키 또한 .env 파일 등으로 환경 변수로 관리하여 .gitignore 파일에 등록해 GitHub 레포지토리에 업로드해서 노출되지 않게 관리하는 부분을 한 번 찾아보시면 이후에도 개발하실 때 큰 도움 되실 것 같습니다.
